### ISSUE TITLE
请问如果我想要将这个模型部署到tensorrt7，需要改哪些文件呢？

### ISSUE THREAD

**Issue by ground-truth** [Qjizhi/TensorRT-CenterNet-3D#2]
请问如果我想要将这个模型部署到tensorrt7，需要改哪些文件呢？
在tensorrt7运行engine出现了这个问题
ed: Bad file descriptor
----------------------------------------------------------------
Input filename:   model/ddd_3dop.onnx
ONNX IR version:  0.0.0
Opset version:    0
Producer name:    
Producer version: 
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by Qjizhi** [comment]
You may refer to this https://github.com/dlunion/tensorRTIntegrate, I run it successfully.

**Comment by Qjizhi** [comment]
> ## 请问如果我想要将这个模型部署到tensorrt7，需要改哪些文件呢？
> 在tensorrt7运行engine出现了这个问题
> ed: Bad file descriptor
> ## Input filename: model/ddd_3dop.onnx
> ONNX IR version: 0.0.0
> Opset version: 0
> Producer name:
> Producer version:
> Domain:
> Model version: 0
> Doc string:
> terminate called after throwing an instance of 'std::bad_alloc'
> what(): std::bad_alloc
> Aborted (core dumped)

You may refer to this https://github.com/dlunion/tensorRTIntegrate, I run it successfully.
